### PR TITLE
support for jhipster generator >= 4.7.0

### PR DESCRIPTION
**Pull request by finxster**
I was trying to use the google-maps generator without success, and then I realized that it doesn't have support for newer jhipster versions.  So I've created a new generator using the most recent version, and then updated this repo. I could make it work for AngularJS 1.x, but I need to work a little more to support Angular 4.

I tested with both saas/without sass versions. You can check it working here: https://github.com/finxster/googlemaps-generator-example

This PR should address https://github.com/moifort/generator-jhipster-google-maps/issues/6 and https://github.com/moifort/generator-jhipster-google-maps/issues/5

### CODE REVIEW

**Comment by jlopezjuy** [comment]
this work on angular2 ?

**Comment by finxster** [comment]
@jlopezjuy no, I couldn't make it work. To be more specific, I'll need to figure out how to add the angular dependency in the code. Any help is welcome.

**Comment by finxster** [comment]
@pascalgrimaud @moifort any update on this? Thanks

**Comment by pascalgrimaud** [comment]
Oh sorry, completely forgot this.
I will review it and merge asap

**Comment by pascalgrimaud** [comment]
Quick tests and it seems OK.
I don't have really time to do full review and tests, as I don't use this module...
So I'm trusting you and will do a release.

**Comment by pascalgrimaud** [comment]
I don't have right to publish to https://www.npmjs.com/package/generator-jhipster-google-maps
So I think we will stay like this

@finxster : feel free to make a new module for google-maps if you have the motivation and want to support for Angular too

**Comment by finxster** [comment]
Thanks, @pascalgrimaud ! Yeah, my next project probably will be with Angular and I'll create a module for that :)

**Pull request merged**
